<!-- theme: jekyll-theme-slate -->
theme: minima
title: Tsubasa Kotani's Homepage

header_pages:
  - index.md
  - research.md

footer_text: "Copyright  © 2024 Tsubasa Kotani. All rights reserved."
url: "https://www.researchgate.net/profile/Tsubasa-Kotani"
description: "小谷翼のホームページです"

